# Generated by Django 3.0.2 on 2020-01-22 12:20

from django.db import migrations, models
import django.db.models.deletion
import memes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=50, null=True, verbose_name='Caption')),
                ('image', models.ImageField(blank=True, null=True, upload_to=memes.models.upload, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=memes.models.upload_image, verbose_name='Image')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memes.Home', verbose_name='Post')),
            ],
        ),
    ]
