# Generated by Django 3.0.2 on 2020-01-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20200122_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='message/', verbose_name='Image'),
        ),
    ]
